site_name: Denim Compute - A Cloud Pak for Automation reference implementation
repo_url: https://github.com/ibm-cloud-architecture/denim-compute/

nav:
    - Introduction: index.md
    - Use case:
        - Use case definition: ./usecase/use-case-definition.md
        - Scenario walkthroughs:
            - Introduction: ./usecase/scenarios-intro.md
            - Main scenario: ./usecase/resources/denim-compute-scenario-walkthrough.pdf
            - BACA scenario: ./usecase/baca-scenario-walkthrough.md
            - BAI scenario: ./usecase/bai-scenario-walkthrough.md
    - Environment:
        - OpenShift:
            - Introduction: ./environment/rhos-intro.md
            - Create OCP cluster: ./environment/rhos-create-cluster.md
            - Installing ODM: ./environment/rhos-install-odm.md
            - Installing BAW: ./environment/rhos-install-baw.md
            - Installing BACA: ./environment/rhos-install-baca.md
            - Installing BAI: ./environment/rhos-install-bai.md
            - Installing CM: ./environment/rhos-install-cm.md
    - Design:
        - Workflow: ./design/workflow.md
        - Decisions: ./design/decisions.md
        - Insights: ./design/insights.md
        - Sundries: ./design/sundries.md
    - Development:
        - Workflow: 
            - Introduction: ./development/workflow-intro.md
            - Process flow control: ./development/process-flow-control.md
            - Process services: ./development/process-services.md
            - Process user interface: ./development/process-user-interface.md
            - Case activities: ./development/case-activities.md
            - Case user interface: ./development/case-user-interface.md
            - Workflow for emulated BAI: ./development/bai-emulated-workflow.md
        - Decisions: ./development/decisions.md
        - Insights: ./development/insights.md
        - Capture: ./development/capture.md
        - Sundries: ./development/sundries.md
    - Showtime:
        - Deploy: ./showtime/deploy-solution.md
        - Run: ./showtime/run-solution.md
    - References: references.md

theme: 
  name: material

extra_css: ["extra.css"]
